sonar.projectKey=jero-to_app_gastos
sonar.organization=jero-to

sonar.sources=filtros.py,gastos.py
sonar.tests=tests
sonar.python.version=3.9

sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=.venv/**
